# Generated by Django 4.1 on 2022-11-24 08:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(default=0, null=True)),
                ('account_name', models.CharField(max_length=15, null=True)),
                ('account_type', models.CharField(max_length=20, null=True)),
                ('pin', models.PositiveSmallIntegerField(null=True)),
                ('balance', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15, null=True)),
                ('lastname', models.CharField(max_length=15, null=True)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=10, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=10, null=True)),
                ('nationality', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_supported', models.CharField(max_length=27, null=True)),
                ('wallet_id', models.IntegerField(null=True)),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(max_length=150, null=True)),
                ('transaction_amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('withdraw', 'Withdrawal'), ('deposit', 'deposit')], max_length=10, null=True)),
                ('transaction_charge', models.IntegerField()),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_destination_account', to='Wallet.account')),
                ('original_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_original_account', to='Wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_wallet', to='Wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.BigIntegerField(null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acc', to='Wallet.account')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wall', to='Wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('customer_id', models.IntegerField(null=True)),
                ('bonus', models.IntegerField(null=True)),
                ('recepient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reciept_number', models.IntegerField(null=True)),
                ('reciept_type', models.CharField(choices=[('D', 'debt'), ('C', 'credit')], max_length=10, null=True)),
                ('reciept_file', models.FileField(upload_to='Wallet/')),
                ('account_number', models.IntegerField(null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000, null=True)),
                ('title', models.CharField(max_length=900, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('passive', 'passive')], max_length=7, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('issued_date', models.DateField(null=True)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_term', models.CharField(max_length=100, null=True)),
                ('loan_balance', models.IntegerField(null=True)),
                ('loan_purpose', models.CharField(max_length=100, null=True)),
                ('guarantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_guarentee', to='Wallet.customer')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_wallet', to='Wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('expiry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('card', models.CharField(choices=[('Debit', 'debit'), ('credit', 'credit')], max_length=6, null=True)),
                ('card_security_code', models.CharField(max_length=6, null=True)),
                ('issuer', models.CharField(max_length=33, null=True)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.customer'),
        ),
    ]
