# Generated by Django 4.1 on 2022-08-19 14:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.IntegerField(null=True)),
                ('accountName', models.CharField(max_length=15, null=True)),
                ('accountType', models.CharField(max_length=20, null=True)),
                ('balance', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15, null=True)),
                ('lastname', models.CharField(max_length=15, null=True)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=10, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('DateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('isactive', models.BooleanField()),
                ('currency', models.CharField(max_length=200, null=True)),
                ('pin', models.CharField(max_length=12, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_customer', to='Wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionCode', models.CharField(max_length=10, null=True)),
                ('value', models.IntegerField()),
                ('discription', models.TextField(max_length=100, null=True)),
                ('transactionFee', models.IntegerField()),
                ('transactionType', models.CharField(max_length=10, null=True)),
                ('destinationAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactions_destinationAccount', to='Wallet.customer')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactions_recipient', to='Wallet.customer')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactions_source', to='Wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactions_wallet', to='Wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('PhoneNumber', models.IntegerField()),
                ('Id', models.IntegerField()),
                ('TransactionCost', models.IntegerField()),
                ('Currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ThirdParty_Currency', to='Wallet.customer')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ThirdParty_account', to='Wallet.account')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ThirdParty_location', to='Wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RewardDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('CustomerId', models.IntegerField()),
                ('Bonus', models.IntegerField()),
                ('Transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reward_Transaction', to='Wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('RecieptNumber', models.IntegerField(null=True)),
                ('RecieptType', models.CharField(choices=[('D', 'debt'), ('C', 'credit')], max_length=10, null=True)),
                ('RecieptFile', models.FileField(upload_to='Wallet/')),
                ('AccountNumber', models.IntegerField()),
                ('TotalAmount', models.IntegerField()),
                ('Transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reciept_Transaction', to='Wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Message', models.CharField(max_length=100, null=True)),
                ('Title', models.CharField(max_length=50, null=True)),
                ('notification_id', models.CharField(max_length=20, null=True)),
                ('Status', models.CharField(max_length=100, null=True)),
                ('Date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification_Date', to='Wallet.transactions')),
                ('Recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification_Recipient', to='Wallet.customer')),
                ('Time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification_Time', to='Wallet.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('IssuedDate', models.DateField()),
                ('DueDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('LoanTerm', models.CharField(max_length=100, null=True)),
                ('LoanBalance', models.IntegerField()),
                ('LoanPurpose', models.CharField(max_length=100, null=True)),
                ('Guarantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_Guarentee', to='Wallet.customer')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_wallet', to='Wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardName', models.CharField(max_length=20, null=True)),
                ('CardType', models.CharField(max_length=20, null=True)),
                ('CardNumber', models.IntegerField()),
                ('SecurityCode', models.IntegerField(null=True)),
                ('Pin', models.IntegerField()),
                ('IssuedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ExpiryDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('SerialNumber', models.IntegerField()),
                ('CreditLimit', models.IntegerField()),
                ('Signature', models.CharField(max_length=10, null=True)),
                ('CardStatus', models.CharField(max_length=50, null=True)),
                ('Issuer', models.CharField(max_length=20, null=True)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card_Account', to='Wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card_wallet', to='Wallet.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_wallet', to='Wallet.wallet'),
        ),
    ]
