# Generated by Django 4.1 on 2022-11-22 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Wallet.customer'),
        ),
        migrations.AddField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
